spring:
  jackson:
    default-property-inclusion: NON_ABSENT
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  port: ${PORT:9090}
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
